### ISSUE TITLE
nameが空の時にConnectボタンを押したら出るエラーを解消する

### ISSUE THREAD

**Issue by ihcomega56** [java-women/ChatToolForBeginners#10]
以下の修正でバグが出ちゃってるっぽいので直します。
https://github.com/java-women/ChatToolForBeginners/pull/3

nameが空のときにConnectボタンを押すと
エラーが出る＆`fooさんが接続しました。`のメッセージが出ない。

→空の時は`だれかが接続しました。`とか表示しようかな。

**Comment by zoosm3** [comment]
ななしさんが接続しました、はいかがですか？

**Comment by ihcomega56** [comment]
( ﾟдﾟ)ﾊｯ!それがよいですね！

**Comment by cyoco** [comment]
プルリク放置しすぎて（ごめんなさい）コンフリクトしてたので、対応してマージしました。

てっきり、java側に「ななし」設定するのかと思っていて、jsで設定するって発想がなかったので、
新しい発見できました＾＾

でも、基本的にはクライアントから送られてきた値は信用できないので、java側で設定するのが正しいのかなと思います。ハンズオン用のアプリだし、 #18 の対応もあるので、一旦マージしときました。

**Comment by cyoco** [comment]
あっ、勘違いΣ(￣ロ￣lll)　
 #18 の対応は関係ないですね。

**Comment by ihcomega56** [comment]
@cyoco ありがとうございます〜！
すみません、Java側で対応したかったんですけど正しいやり方がわからなかった…(真顔)
調べて別途リファクタリングしますね(-_-;)
このissueはcloseします！
