### ISSUE TITLE
デザインを何とかする

### ISSUE THREAD

**Issue by ihcomega56** [java-women/ChatToolForBeginners#11]
何とかしようｗ

**Comment by cyoco** [comment]
今週バタバタしてデザイン案出せないかもです。。。

一応、参考になりそうな案（文字情報ですみません）出しときます。

【案１：ポップな感じにするなら】
吹き出しでLINE風に。
（参考）
CSSだけでできそうな参考サイト見つけたので連携。
http://nelog.jp/line-bolloon-css
ただ、自分の発言と他人の発言を識別しなくてはいけないので、
そのあたりの仕組みが課題になるかと。

【案２：シンプルにするなら】
ビジネスライクなチャットツールにするなら、「let's chat」みたいなシンプルな感じがいいかなと。

いずれにしろ、発言した時のタイムスタンプ表示は、入れたいですね。

**Comment by mahya8585** [comment]
プロトタイプの作成なら任せろっ！みんなのアイデアが上がれば図に起こしますよ。
以下は個人イメージです。
- ログイン
  ![login](https://cloud.githubusercontent.com/assets/10239748/12908528/d9b3f706-cf3b-11e5-8a24-ee07dc034cbe.png)
- チャットページ（画像透過と背景色が合ってないのはご愛敬ということにしておいてくださいｗ本番はちゃんと合わせよう）
  文字は下から上へ流れるイメージです。skypeとかslackと一緒ですね。背景は固定で文字だけスクロールします。
  ![chat](https://cloud.githubusercontent.com/assets/10239748/12908530/dca3c5ae-cf3b-11e5-9638-1c8178570a07.png)

**Comment by ihcomega56** [comment]
こんなイメージだ！以上！(ひどい)
![default](https://cloud.githubusercontent.com/assets/8938191/12911197/013916ea-cf54-11e5-8b3b-e533a36b2f1a.png)

**Comment by mahya8585** [comment]
（えーフラットデザインがいいー

**Comment by ihcomega56** [comment]
(ごちゃっとしなくてかわいげがあれば割となんでもいいー
色味がパステルカラーだと可愛いかな、くらいです

**Comment by mahya8585** [comment]
ショッキングピンクだとGTUG、スモークピンクだとPyLadiesと被るから、
どうせなら赤基調がいいかな、とおもったんだけど、赤の明度とか透過率とか変更するとピンクになるのでどうしようもなかった。
というどうでもいい色実験の共有

**Comment by ihcomega56** [comment]
今更ですがここで挙がっているフラットデザインってなに！？
http://liskul.com/cr_flatdesign-5857
これじゃないですよね？

**Comment by ihcomega56** [comment]
↑これはどうでもいいのでスルーして下さいｗ

で、まあやさんのデザイン案でいきましょう👏

**Comment by cyoco** [comment]
ログイン画面はこちらで #22 作業します。
