### ISSUE TITLE
ログイン画面作成する

### ISSUE THREAD

**Issue by cyoco** [java-women/ChatToolForBeginners#22]
ログイン画面とログイン処理の作成。

**Comment by erk5** [comment]
ログイン処理はどはどちらを想定していますか？
- Basic認証
  - サーバ側でユーザID・パスワードを設定してこれをユーザに通知するため簡単
- フォーム認証
  - ユーザ登録画面などで設定したユーザID・パスワードで認証を行うため、データベースなどでのデータ管理やユーザ登録画面を作る必要があるためそれなりに時間がかかる。

後、作れそうですか？
無理そうならやりますよ。

**Comment by erk5** [comment]
フォーム認証でとりあえず作ります！

**Comment by erk5** [comment]
#46 でフォーム認証を作成しました。
ユーザが固定になっているのでどうするか決めて実装する。→別issueを作成する。

**Comment by cyoco** [comment]
ログイン画面ができたのでcloseします。
