### ISSUE TITLE
参加者演習用プロジェクトを作成する

### ISSUE THREAD

**Issue by zoosm3** [java-women/ChatToolForBeginners#23]
chat-tutorialとは別に、ハンズオン参加者演習用の空プロジェクトを用意する。

**Comment by erk5** [comment]
参加者用はブランチで切り替えてはどうでしょう？
・chapter1→空プロジェクト
・・・　
・final→完成プロジェクト

途中正解のプロジェクト用のブランチも切れるので途中で置いてかれてしまった人も
今から説明するとことはこのブランチからやってね～と言えれば復帰も出来るかなと思いました。
(Git使えない人だと厳しいけど)

**Comment by zoosm3** [comment]
@erk5 コメントありがとうございます。
ログイン機能のpull requestがmasterにマージされたら参加者用プロジェクトをpushしたいので確認です。
今回ネットワークのこともあり、ハンズオン会場でブランチのcloneから始められないようです。
途中経過をブランチで切るのはなく、演習用にファイルが揃ったプロジェクトを事前にcloneして用意してもらうほうが良いと思います。いかがでしょうか。

**Comment by erk5** [comment]
@zoosm3 
そうですね、ネットワークのことを考えると全部そろっているほうが良いですね。
下記のようにディレクトリで分けるイメージですかね。

top
∟init
　　∟chat-tutorial　　←　演習用の初期プロジェクト
∟chapter1
　　∟chat-tutorial　　←　必要であれば演習途中のプロジェクト
∟complete
　　∟chat-tutorial　　←　完成版のプロジェクト

事前準備でcloneしてこなかった人用にいくつかUSBに入れて用意しておいたほうが良さそうですね。

**Comment by zoosm3** [comment]
@erk5 
今回は規模が小さいので途中経過分までは必要ないかと思います。
クラスを一通り揃えた演習用の初期プロジェクトを作成しましたので、ご確認をお願いします。
https://github.com/java-women/ChatToolForBeginners/tree/master/chat-exercise

**Comment by erk5** [comment]
確認しました。
ざっとコメント記載します。
- eclipse固有の設定ファイルなどは削除したほうが良いです。
- インデントが崩れているので再フォーマットしたほうが良いかも。
- pom.xmlのwebsocketは削除しておいたほうが良いと思います。
- 以下のクラスは初期プロジェクトではなしで、演習で作ってもらったほうが良いと思います。
  - App.javaは
  - HelloController.java
  - ChatController.java
  - StompConfig.java
  - chat.html
- WebSecurityConfig.javaのconfigureGlobalメソッドの中身はからにして欲しいです。
- javajo.jsは穴埋めにしてほしいです。

masterに直接Pushはなるべく避けてPRでやってもらえるとありがたいです。
コメント書けないので。。。

**Comment by zoosm3** [comment]
設定ファイルの削除以外対応しました。
https://github.com/java-women/ChatToolForBeginners/pull/54
