### ISSUE TITLE
背景画像の差し替え

### ISSUE THREAD

**Issue by cyoco** [java-women/ChatToolForBeginners#28]
#26 の指摘対応。

元画像をもらって、スケルトン加工はjsでやる。

**Comment by AyaEbata** [comment]
@cyoco さん
元画像持っているので、あやから渡しましょうか？（背景なしver.の画像でいいですかね

画像コミットするついでにこちらで修正したら手取り早いと思ったのですが、
透過の方法がcssのopacityしかわからなかったので。。。（調べてもcssばっか引っかかるとかいう

（これ使ったら行けるかも、的な何かあればやってみます！

**Comment by AyaEbata** [comment]
@cyoco さん
やっときまっせ

**Comment by AyaEbata** [comment]
Issue #39 で対応済みなためクローズします。
