### ISSUE TITLE
Hello〜の変更

### ISSUE THREAD

**Issue by cyoco** [java-women/ChatToolForBeginners#29]
#26 の指摘対応。

元のサンプルHello〜の変数の変更。
チャット画面も「hello.html」だと違和感あるので、ファイル名もできれば直したい。

**Comment by AyaEbata** [comment]
@cyoco さん
これだれもアサインされてないみたいなので、誰もまだ手をつけてないのならばやりましょーかー？

ファイル名と変数名でHello~をwelcomとかchatとかに変更するという認識ですかね。

ちなみに、
https://docs.google.com/presentation/d/1ln7Y2FRYnvhv6GwmJgO1fLxV5ULjLt4wwgT-Eomzc_Y/edit#slide=id.g44a191af46fec104_39
にて、HelloControllerとありますが、ここはあえてHelloのままにしておく、という感じですか？

**Comment by cyoco** [comment]
chatController作ったので、HelloControllerはそのままで良いかと。

いい感じの命名できたら、変えちゃってもいいです！
