### ISSUE TITLE
ログイン成功画面を作成する

### ISSUE THREAD

**Issue by AyaEbata** [java-women/ChatToolForBeginners#36]
welcome.html

ようこそ○○さん
チャットツールへ（←ボタン）

**Comment by AyaEbata** [comment]
画面側は作成済み。

### 残作業
- 名前の受け渡し

**Comment by erk5** [comment]
@AyaEbata 
ログイン機能作っているのでこちら引き取ります～

**Comment by erk5** [comment]
#46 でログインユーザの名前が表示されるようにしました。
確認＆PRがMergeされたら本Issueクローズしちゃってください～

**Comment by AyaEbata** [comment]
@erk5 さん
ありがとうございます！承知いたしました。

**Comment by AyaEbata** [comment]
PR #46 でマージされたのでクローズします。
