### ISSUE TITLE
ユーザ登録方法を決めてログイン処理に追加する

### ISSUE THREAD

**Issue by erk5** [java-women/ChatToolForBeginners#47]
ユーザ登録方法
- 固定　→　ハードコーディング
- 各自ユーザを作成できるようにする　→　ユーザ登録画面を作成し、インメモリDBにユーザ情報を保持しておく

**Comment by erk5** [comment]
@cyoco 
ログイン処理時のユーザはどのように作成しますか？

**Comment by cyoco** [comment]
今回は、ローカルで実装してもらうので、自分たちで好きなユーザID、パスワードを演習の中で設定してもらえればいいので、
固定　→　ハードコーディング
で良い気がします。

**Comment by erk5** [comment]
#51 がMergeされたためCloseします。
