### ISSUE TITLE
関ジャバ仕様→Java女子部仕様に変更

### ISSUE THREAD

**Issue by ihcomega56** [java-women/ChatToolForBeginners#5]
パッケージ名とpom.xmlの中身を修正する
- パッケージ名
  `/ChatToolForBeginners/chat-tutorial/src/main/java/kanjava`
  -> `/ChatToolForBeginners/chat-tutorial/src/main/java/javajo`とか？
- pom.xml
  `/ChatToolForBeginners/chat-tutorial/pom.xml`
  `groupId`と`start-clas`の値を修正

**Comment by cyoco** [comment]
dockerfileとかも今回不要なので、削除する。
