### ISSUE TITLE
Chat画面にLogoutボタンを追加する

### ISSUE THREAD

**Issue by erk5** [java-women/ChatToolForBeginners#50]

**Comment by AyaEbata** [comment]
welcome画面では右上にlogoutボタンを設置してしまったのですが、chat画面では現在右上にはdisconnectボタンがあります。
場所を統一させるためにもwelcome画面のlogoutボタンの移動もする必要ありですね。

**Comment by erk5** [comment]
- Disconnectボタンは右下(チャットの入力系は下段にまとめる)
- Loginボタン右上(Welcome画面と統一)

でどうでしょう。
良さそうであれば対応お願いできますか？

**Comment by AyaEbata** [comment]
@erk5 さん

承知いたしました！
それでやってみますーー！
やってみて微妙でしたら

**Comment by AyaEbata** [comment]
変更するかもしれませんが。(途中で送っちゃいました)

**Comment by AyaEbata** [comment]
@erk5 さん
#23 でディレクトリの変更があったと思いますが、両方のディレクトリにこの変更を適用させて大丈夫でしょうか？？

**Comment by erk5** [comment]
@AyaEbata 
chat-tutorialだけで良いですよ～

**Comment by AyaEbata** [comment]
@erk5 さん
フロントはいい感じにできたのですが、logoutできないです。。。
フロントはwelcome画面と同じfromを指定してあげているのですが、何かそれ以外に実装するものってあるのでしょうか？

**Comment by erk5** [comment]
@AyaEbata 
あー、
chat.html普通のHTMLだからjavascriptでPOSTしないとダメかも。。。
Thymeleafにすればweclome画面と同じようにできます。

**Comment by erk5** [comment]
#53 が完了したのでCloseします。
